services:
  - type: web
    name: brightworks-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://brightworks:4heM5D6ER6s2XUUW@cluster0.9zhmytf.mongodb.net/brightwork?retryWrites=true&w=majority
      - key: BACKEND_URL
        value: https://brightsbrokscleanproclean2026.onrender.com
      - key: VITE_API_URL
        value: https://brightsbrokscleanproclean2026.onrender.com
