services:
  - type: web
    name: appcleanpremium-backend
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "7d"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PUSH_PUBLIC_KEY
        sync: false
      - key: PUSH_PRIVATE_KEY
        sync: false

  - type: static
    name: appcleanpremium-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_PUSH_PUBLIC_KEY
        sync: false
