import {
  LayoutDashboard,
  Calendar as CalendarIcon,
  CalendarDays,
  BookOpen,
  Bell,
  DollarSign,
  Quote,
  Building2,
  Users,
  Settings,
  Star,
  Mail,
} from 'lucide-react'
import { NavItem } from './types'

export const navigationItems: NavItem[] = [
  {
    name: 'Dashboard',
    href: '/dashboard',
    icon: LayoutDashboard,
    roles: ['admin'],
    permission: 'dashboard',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    name: 'Schedule',
    href: '/schedule',
    icon: CalendarIcon,
    roles: ['admin', 'employee'],
    permission: 'schedule',
    color: 'from-purple-500 to-pink-500',
  },
  {
    name: 'Calendar',
    href: '/calendar',
    icon: CalendarDays,
    roles: ['admin'],
    permission: 'calendar',
    color: 'from-indigo-500 to-purple-500',
  },
  {
    name: 'Notes',
    href: '/notes',
    icon: BookOpen,
    roles: ['admin'],
    permission: 'notes',
    color: 'from-amber-500 to-orange-500',
  },
  {
    name: 'Reminders',
    href: '/reminders',
    icon: Bell,
    roles: ['admin'],
    permission: 'reminders',
    color: 'from-red-500 to-rose-500',
  },
  {
    name: 'Expenses',
    href: '/expenses',
    icon: DollarSign,
    roles: ['admin'],
    permission: 'expenses',
    color: 'from-emerald-500 to-teal-500',
  },
  {
    name: 'Quotes',
    href: '/quotes',
    icon: Quote,
    roles: ['admin'],
    permission: 'quotes',
    color: 'from-violet-500 to-purple-500',
  },
  {
    name: 'Clients',
    href: '/clients',
    icon: Building2,
    roles: ['admin'],
    permission: 'clients',
    color: 'from-sky-500 to-blue-500',
  },
  {
    name: 'Satisfaction',
    href: '/customer-satisfaction',
    icon: Star,
    roles: ['admin'],
    permission: 'clients',
    color: 'from-yellow-500 to-amber-500',
  },
  {
    name: 'Users',
    href: '/users',
    icon: Users,
    roles: ['admin'],
    permission: 'users',
    color: 'from-pink-500 to-rose-500',
  },
  {
    name: 'Settings',
    href: '/settings',
    icon: Settings,
    roles: ['admin'],
    permission: 'settings',
    color: 'from-slate-500 to-gray-500',
  },
  {
    name: 'Email Notifications',
    href: '/email-notifications',
    icon: Mail,
    roles: ['superadmin' as const],
    permission: 'settings',
    color: 'from-cyan-500 to-blue-500',
  },
]

